# Generated by Django 5.0.6 on 2024-07-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Admin', 'Admin')], max_length=255),
        ),
    ]
