# Generated by Django 5.0.6 on 2024-07-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=255),
        ),
    ]
