# Generated by Django 4.0.6 on 2024-10-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_group_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='groups',
        ),
    ]
