# Generated by Django 4.0.6 on 2024-11-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_group_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=255),
        ),
    ]
