# Generated by Django 4.0.6 on 2024-10-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Question', '0002_choices_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20)),
                ('count_questions', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(to='Question.question')),
            ],
        ),
    ]
