# Generated by Django 4.0.6 on 2024-10-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizes',
            old_name='level',
            new_name='lv',
        ),
    ]
