# Generated by Django 4.0.6 on 2024-10-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0002_rename_level_quizes_lv'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='mark_total',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
