# Generated by Django 4.0.6 on 2024-10-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0003_quizes_mark_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizes',
            name='mark_total',
            field=models.FloatField(),
        ),
    ]
