# Generated by Django 4.0.6 on 2024-10-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_category_name'),
        ('Quizes', '0004_alter_quizes_mark_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
    ]
