# Generated by Django 4.0.6 on 2024-11-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0005_quizes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizes',
            name='lv',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Intermidate', 'Intermidate'), ('Advanced', 'Advanced')], max_length=20),
        ),
    ]
